### PR TITLE
use boost/std-agnostic shared_ptrs for urdf types

### PR DESCRIPTION
**Pull request by guihomework**
needed for bionic build, and is backward compatible with kinetic (since it is boost/std-agnostic)

### CODE REVIEW

**Comment by AndriyPt** [comment]
@guihomework please open PR for melodic-devel branch

**Comment by guihomework** [comment]
But this PR is valid too, as it works on kinetic, don't you want to merge it there too ?

**Comment by AndriyPt** [comment]
@guihomework I'd prefer to avoid changing things if it is not necessary :) If you do not need it in kinetic please close it. If you do need it please let me know. ROS Melodic PR was merged.

**Comment by guihomework** [comment]
ok. we don't need it (we run our own branch, with tactile changes, and just try port what is not ubi related to you as soon as possible, for maintainability.

**Pull request closed without merging**
