### PR TITLE
Revert "removing deprecated sr hand package"

### PR DESCRIPTION
**Pull request by mikramarc**
Reverts shadow-robot/sr_core#207

### CODE REVIEW

**Review by beatrizleon — APPROVED** [review]

**Comment by lianghongzhuo** [comment]
what's going on here? I just report 5 issues about removing this package. Now you move the package back?

**Comment by lianghongzhuo** [comment]
Next time, please test and check another package dependency before you push important changes to the working branch!

**Comment by mikramarc** [comment]
Hi @lianghongzhuo
Of course we always test and check our changes thoroughly. However, recently we've had a major change in our codebase which caused a little bit of a temporary chaos. The package in question will be brought back with this PR most likely early tomorrow.

**Comment by lianghongzhuo** [comment]
OK, I will close these issues then.

**Review by maxzieba — APPROVED** [review]

**Pull request merged**
