### PR TITLE
setup.py: Use setuptools instead of distutils

### PR DESCRIPTION
**Pull request by rhaschke**
See http://wiki.ros.org/noetic/Migration#Setuptools_instead_of_Distutils

### CODE REVIEW

**Review by biofotis — CHANGES_REQUESTED** [review]
I made the checks public now  could you please have a look?

**Comment by rhaschke** [comment]
I cannot yet access the logs. It states:
```
Logs are disabled
Logs are not available because of project configuration. To enable the viewing or downloading of logs in the build results, contact the CodeBuild project owner.
```

**Comment by biofotis** [comment]
> I cannot yet access the logs. It states:
> 
> ```
> Logs are disabled
> Logs are not available because of project configuration. To enable the viewing or downloading of logs in the build results, contact the CodeBuild project owner.
> ```

Yes because I initiated the last build to test it. If you commit again you will be able to see them.

**Comment by rhaschke** [comment]
I still can't access the logs.

**Comment by biofotis** [comment]
> I still can't access the logs.

now it should be fine and accessible

**Review by biofotis — APPROVED** [review]

**Pull request merged**
