### PR TITLE
Update tactile_receiver.py

### PR DESCRIPTION
**Pull request by lianghongzhuo**
## Proposed changes
remove the warning `No tactile topic found. This is normal for a simulated hand`
as it is confusing, only UBI0 type got a warning but PST and biotac don't get the warning.
So either remove the warning or also add a warning for biotac and pst tactile type.

## Checklist

If the task is applicable to this pull request (see applicability criteria in brackets), make sure it is completed before checking the corresponding box. Otherwise, tick the box right away. Make sure that **ALL** boxes are checked **BEFORE** the PR is merged.

- [x] Manually tested that added code works as intended (if any functional/runnable code is added).
- [x] Added automated tests (if a new class is added (Python or C++), interface of that class must be unit tested).
- [x] Tested on real hardware (if the changed or added code is used with the real hardware).
- [x] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc.)

### CODE REVIEW

**Comment by mikramarc** [comment]
Hi @lianghongzhuo 
Thank you for the contribution. The warning still seems to be useful, if you please could add the warnings for other types of tactiles as mentioned in your comment I'll be happy to merge.

**Comment by lianghongzhuo** [comment]
Thanks, I will update the pr, I also propose to add the timeout a lit bit longer, as in our system 1 second is too short, I always got a warning that says: `no tactile found` even if I have a pst tactile sensor.
Change the timeout to 5 seconds can fix this.

**Comment by mikramarc** [comment]
@lianghongzhuo longer timeout sounds good to me!

**Comment by lianghongzhuo** [comment]
@mikramarc I updated the pr, please review.

**Comment by mikramarc** [comment]
@lianghongzhuo Actually, in order to avoid multiple warnings we'd rather have this kind of setup:

```
    def find_tactile_type(self):
        try:
            rospy.wait_for_message(
                self._prefix + "tactile", ShadowPST, timeout=5.0)
            return "PST"
        except (rospy.ROSException, rospy.ROSInterruptException):
            pass

        try:
            rospy.wait_for_message(
                self._prefix + "tactile", BiotacAll, timeout=5.0)
            return "biotac"
        except (rospy.ROSException, rospy.ROSInterruptException):
            pass

        try:
            rospy.wait_for_message(
                self._prefix + "tactile", UBI0All, timeout=5.0)
            return "UBI0"
        except (rospy.ROSException, rospy.ROSInterruptException):
            pass

        rospy.logwarn("No supported tactile topic found. This is normal for a simulated hand")
        return None
```
        
Does that work for you?

**Comment by lianghongzhuo** [comment]
Yes, this is great! Do you want me to modify it? or you want to do it on your side?

**Comment by mikramarc** [comment]
@lianghongzhuo please do it and I'll approve :)

**Comment by lianghongzhuo** [comment]
Done

**Review by maxzieba — APPROVED** [review]

**Comment by mikramarc** [comment]
@lianghongzhuo maybe extend the timeout for all tactile types as you suggested before?

**Comment by lianghongzhuo** [comment]
these three sensors are checked one by one. So for the last two sensors, there is already a large time before checking the topic (5 seconds and 10 seconds). Then the tactile topic should already be launched by then.
If every topic check needs 5 seconds, then it will take 15 seconds in total if we do not have the tactile sensor (in simulation).

**Review by mikramarc — APPROVED** [review]

**Review by georgiablanco — APPROVED** [review]

**Pull request merged**
